run_id: "gpt-numerics-v1"
reference: {{ device: cpu, dtype: fp32, compile: false }}
devices: [cpu, mps]
compile_modes: [false, true]
dtype_policies: [fp32, bf16, fp16, autocast_bf16]
decoding:
  mode_open_loop: {{ enabled: true }}
  mode_closed_loop: {{ enabled: true, max_new_tokens: 256 }}
sampling:
  temperature: 0.0
  top_p: 1.0
controls:
  deterministic: true
  force_fp32_accum_attention: true
  force_fp32_accum_norms: true
  kv_cache_dtype: "fp16"            # or "bf16" / "fp32"; held constant
  rope_cache_dtype: "fp32"
dataset:
  shard_pattern: "/data/fineweb/fineweb_train_000001.bin"
# or:
#  path: "prompts.jsonl"
#  min_prompts: 200
  max_prompts: 500
  length_buckets: [64, 512, 2048]
metrics:
  topk: [1, 5, 10]
  margin_bins: [0.1, 0.5, 1.0]
outputs:
  root: "./artifacts_root"
  write_parquet: true