# Logging
wandb_log: true
wandb_project: 'daisy-wee'
wandb_run_name: '350m-fine-tune-fineweb'
# Torch config
torch.coordinate_descent_tuning: true
# Pretraining checkpoint path
init_checkpoint: "checkpoints/20251011T1549-val2.770-step005000-run1-best.pt"
# Instruct SFT training configuration
train_shards: "data/fineweb/fineweb_train_*.bin"
target_tokens: 4000000000
cooldown_frac: 0.7
learning_rate_schedule: linear_warmup_cosine_decay
training_sequence_length: 65536        #  N * 1024; must be divisible by window_block_size
train_attention_window_len: 3456        # largest sliding attention window used during training; must be divisible by window_block_size
# Optimizers configuration
optimizers:
  - type: AdamW
    betas: [0.9, 0.999]
    eps: 1.0e-10
    weight_decay: 0.01
    fused: true
    params:
      - group: head_params
        lr: 3.1e‑5
      - group: embed_params
        lr: 0.0
      - group: scalar_params
        lr: 1.5e‑4
  - type: Muon
    momentum: 0.95
    weight_decay: 0.01
    params:
      - group: hidden_matrix_params
        lr: 2.5e‑4
full_windows: true
# Gradient accumulation
grad_acc_steps: 1 # assumes world_size=8
# Evaluations
val_shards:
  - type: "fineweb"
    path: "data/fineweb/fineweb_val_000000.bin"
  - type: "fineweb-edu"
    path: "data/fineweb-edu/edu_fineweb_val_000000.bin"
val_loss_every_tokens:     104857600
val_seq_len: 262144       # 4 * 64 * 1024
tot_val_tokens: 10485760
# Snapshots
snapshot_warmup_tokens:   0     # token warmup before snapshots
snapshot_per_n_tokens:     0         # snapshot interval by tokens
save_checkpoint: true
# Model Definition
model_spec: gpt2_350m