# Logging
wandb_log: true
wandb_project: 'daisy-wee'
wandb_run_name: 'instruct_sft_1.6B'
# Pretraining checkpoint path
init_checkpoint: "checkpoints/state_step_100000.pt"
# Instruct SFT training configuration
train_shards: "data/instruct_mix/instruct_train_*.bin"
val_shards: "data/instruct_mix/instruct_val_*.bin"
val_seq_len: 262144             # 64 * 1024
target_tokens: 700000000            # total training tokens
cooldown_frac: 0.9
# Optimizers configuration
optimizers:
  - type: AdamW
    betas: [0.9, 0.95]
    eps: 1.0e-10
    weight_decay: 0.01
    fused: true
    params:
      - group: head_params
        lr: 0.0027  # keep head LR similar to pretrain 1.6B unless specified
      - group: embed_params
        lr: 0.002
      - group: scalar_params
        lr: 0.002

  - type: Muon
    momentum: 0.95
    params:
      - group: hidden_matrix_params
        lr: 0.02
full_windows: true
# Common settings
tot_val_tokens: 10485760
val_loss_every_tokens: 50000000
snapshot_warmup_tokens: 0           # token warmup before snapshots
snapshot_per_n_tokens: 200000000                # snapshot interval by tokens
save_checkpoint: true
# Model settings
model_spec: gpt2_1p6b
training_sequence_length: 16384     #  64 * 1024
train_attention_window_len: 3456


