# Pretraining checkpoint path
init_checkpoint: "checkpoints/state_step_100000.pt"
# Instruct SFT training configuration
train_files: "data/instruct_mix/instruct_train_*.bin"
val_files: "data/instruct_mix/instruct_val_*.bin"
val_seq_len: 262144       # 64 * 1024
num_iterations: 1000        # assumes 8x GPUs, 400 for 1x GPU
cooldown_frac: 0.9
embed_params_lr: 0.002          #adamw: default 0.3
scalar_params_lr: 0.002         #adamw: default 0.015
hidden_matrix_params_lr: 0.02   #muon: default 0.025
adamw_weight_decay: 0.01        # default 0.01
# Common settings
val_tokens: 10485760
val_loss_every: 50
val_snapshot_every: 2     # in terms of val iterations, not steps
snapshot_skip: 0         # skip snaps for the first N val iterations
save_checkpoint: true
# Model settings
max_seq_len: 16384      # 64 * 1024
vocab_size: 50257
num_layers: 48
head_dim: 64              # default: 128
num_heads: 25
model_dim: 1600

model_type: gpt2
