# Logging
wandb_log: true
wandb_project: 'daisy-wee'
wandb_run_name: '150m-instruct'
# Torch config
torch.coordinate_descent_tuning: false
# Pretraining checkpoint path
init_checkpoint: "checkpoints/20251018T0048-val3.030-step001908-run1-final.pt"
# Instruct SFT training configuration
train_shards: "data/instruct_mix/instruct_train_*.bin"
target_tokens: 173015040
cooldown_frac: 0.95
learning_rate_schedule: linear_warmup_cosine_decay
training_sequence_length: 65536        #  N * 1024; must be divisible by window_block_size
train_attention_window_len: 1792        # largest sliding attention window used during training; must be divisible by window_block_size
# Optimizers configuration
optimizers:
  - type: AdamW
    betas: [0.9, 0.999]
    eps: 1.0e-10
    weight_decay: 0.01
    fused: true
    params:
      - group: head_params
        lr: .0003125
      - group: embed_params
        lr: 0.03
      - group: scalar_params
        lr: .0015
  - type: Muon
    momentum: 0.95
    weight_decay: 0.01
    params:
      - group: hidden_matrix_params
        lr: .0025
full_windows: true
# Gradient accumulation
grad_acc_steps: 1 # assumes world_size=8
# Evaluations
val_shards:
  - type: "instruct-mix"
    path: "data/instruct_mix/instruct_val_*.bin"
  - type: "fineweb-edu"
    path: "data/fineweb-edu/edu_fineweb_val_000000.bin"
val_loss_every_tokens:     26214400
val_seq_len: 262144       # 4 * 64 * 1024
tot_val_tokens: 10485760
# Checkpoints
checkpoint_warmup_tokens:     1     # token warmup before checkpoints
checkpoint_per_n_tokens:     1         # checkpoint interval by tokens
save_checkpoint: true
# Model Definition
model_spec: gpt2_150m