# Pretraining configuration
train_files: "data/fineweb/fineweb_train_*.bin"
val_files: "data/fineweb/fineweb_val_*.bin"
val_seq_len: 262144       # 4 * 64 * 1024
num_iterations: 5960
cooldown_frac: 0.7
# Common settings
val_tokens: 10485760
val_loss_every: 200
save_checkpoint: true
val_snapshot_every: 1000
# Model settings
max_seq_len: 65536      # N * 1024, max_sequence_length
vocab_size: 50257
num_layers: 16
head_dim: 128             # documented here as static
num_heads: 8
model_dim: 1024           # num_heads * head_dim