# Logging
wandb_log: true
wandb_project: 'daisy-wee'
wandb_run_name: '150m'
# Torch config
torch.coordinate_descent_tuning: true
# Pretraining configuration
train_shards: "data/fineweb-edu/edu_fineweb_train_*.bin"
target_tokens: 7000000000
cooldown_frac: 0.2
learning_rate_schedule: constant_with_linear_decay
training_sequence_length: 65536        #  N * 1024; must be divisible by window_block_size
train_attention_window_len: 1792        # largest sliding attention window used during training; must be divisible by window_block_size
# Optimizers configuration
optimizers:
  - type: AdamW
    betas: [0.8, 0.95]
    eps: 1.0e-10
    weight_decay: 0.0
    fused: true
    params:
      - group: head_params
        lr: 0.004
      - group: embed_params
        lr: 0.2
      - group: scalar_params
        lr: 0.015

  - type: Muon
    momentum: 0.95
    weight_decay: 0.0
    params:
      - group: hidden_matrix_params
        lr: 0.02
full_windows: false
# Gradient accumulation
grad_acc_steps: 1
# Evaluations
val_shards:
  - type: "fineweb-edu"
    path: "data/fineweb-edu/edu_fineweb_val_*.bin"
val_loss_every_tokens:     52428800
val_seq_len: 262144       # 4 * 64 * 1024
tot_val_tokens: 10485760
# Checkpoints
checkpoint_warmup_tokens:   209715200     # token warmup before checkpoints
checkpoint_per_n_tokens:     52428800         # checkpoint interval by tokens
save_checkpoint: true
# Model Definition
model_spec: gpt2_150m