# Logging
wandb_log: true
wandb_project: 'daisy-wee'
wandb_run_name: '350m'
# Pretraining configuration
train_shards: "data/fineweb/fineweb_train_*.bin"
target_tokens: 3000000000
cooldown_frac: 0.7
embed_params_lr: 0.02
scalar_params_lr: 0.02
hidden_matrix_params_lr: 0.025
adamw_weight_decay: 0.01
# Evaluations
val_shards: "data/fineweb/fineweb_val_*.bin"
val_loss_every_tokens:     13000000
val_seq_len: 262144       # 4 * 64 * 1024
val_tokens: 10485760
# Snapshots
snapshot_warmup_tokens:   100000000     # token warmup before snapshots
snapshot_per_n_tokens:     26000000         # snapshot interval by tokens
save_checkpoint: true
# Model Definition
model_type: gpt2
max_seq_len: 65536        # N * 1024, max_sequence_length
vocab_size: 50257
num_layers: 16
head_dim: 128             # documented here as static
num_heads: 8
model_dim: 1024           # num_heads * head_dim