# Logging
wandb_log: true
wandb_project: 'daisy-wee'
wandb_run_name: '350m'
# Pretraining configuration
train_shards: "data/fineweb/fineweb_train_*.bin"
target_tokens: 3000000000
cooldown_frac: 0.7
training_sequence_length: 65536        #  N * 1024
attention_window_tokens: 3456          # sliding window trained span
window_block_size: 128                 # must divide both training_sequence_length and attention_window_tokens
# Optimizers configuration
optimizers:
  - type: AdamW
    betas: [0.0, 0.0]
    eps: 1.0e-10
    weight_decay: 0.0
    fused: false
    params:
      - group: head_params
        lr: 0.02
      - group: embed_params
        lr: 0.3
      - group: scalar_params
        lr: 0.015

  - type: Muon
    momentum: 0.95
    params:
      - group: hidden_matrix_params
        lr: 0.025
full_windows: false
# Gradient accumulation
grad_acc_steps: 1
# Evaluations
val_shards: "data/fineweb/fineweb_val_*.bin"
val_loss_every_tokens:     52428800
val_seq_len: 262144       # 4 * 64 * 1024
val_tokens: 10485760
# Snapshots
snapshot_warmup_tokens:   209715200     # token warmup before snapshots
snapshot_per_n_tokens:     52428800         # snapshot interval by tokens
save_checkpoint: true
# Model Definition
model_spec: gpt2_350m

