# Logging
wandb_log: true
wandb_project: 'daisy-wee'
wandb_run_name: 'test-tiny'
# Pretraining configuration
train_shards: "data/fineweb/fineweb_train_*.bin"
target_tokens: 1000000
cooldown_frac: 0.7
training_sequence_length: 1024        #  N * 1024; must be divisible by window_block_size
attention_window_len: 1024             # largest sliding attention window used during training; must be divisible by window_block_size
# Optimizers configuration
optimizers:
  - type: AdamW
    betas: [0.9, 0.95]
    eps: 1.0e-10
    weight_decay: 0.1
    fused: true
    params:
      - group: head_params
        lr: 0.02
      - group: embed_params
        lr: 0.3
      - group: scalar_params
        lr: 0.015

  - type: Muon
    momentum: 0.95
    params:
      - group: hidden_matrix_params
        lr: 0.025
full_windows: false
# Gradient accumulation
grad_acc_steps: 1
# Evaluations
val_shards: "data/fineweb/fineweb_val_*.bin"
val_loss_every_tokens:     65536
val_seq_len: 262144       # 4 * 64 * 1024
tot_val_tokens: 10485760
# Snapshots
snapshot_warmup_tokens:   0     # token warmup before snapshots
snapshot_per_n_tokens:     0         # snapshot interval by tokens
save_checkpoint: false
# Model Definition
model_spec: test-tiny-model